---
# tasks file for kube_tools

- name: print distro info
  debug: msg="{{ ansible_os_family }} > {{ ansible_distribution }} {{ ansible_distribution_version }}"

- name: Include checks/asserts
  include: asserts.yml
