---
# tasks file for kube_tools

- name: Include checks/asserts
  include: asserts.yml

- name: Get and install kubectl binary
  get_url:
    url: "{{ kubectl_url }}"
    dest: "{{ binary_path }}"
    mode: '0755'

- name: Get and install kubectx binary
  get_url:
    url: "{{ kubectx_url }}"
    dest: "{{ binary_path }}"
    mode: '0755'

- name: Get and install kubens binary
  get_url:
    url: "{{ kubens_url }}"
    dest: "{{ binary_path }}"
    mode: '0755'

- name: Get helm
  get_url:
    url: "{{ helm_url }}"
    dest: /tmp
    checksum: "{{ helm_checksum }}"
  delegate_to: localhost

- name: Unarchive helm
  unarchive:
    src: "/tmp/{{ helm_archive_file }}"
    dest: /tmp
  delegate_to: localhost

- name: Install helm binary
  copy:
    src: "/tmp/{{ helm_binary_file }}"
    dest: "{{ binary_path }}"
    mode: '0755'

- name: Get and install fluxctl binary
  get_url:
    url: "{{ fluxctl_url }}"
    dest: "{{ binary_path }}/fluxctl"
    mode: '0755'

- name: Get istioctl
  get_url:
    url: "{{ istioctl_url }}"
    dest: /tmp
  delegate_to: localhost

- name: Unarchive istioctl
  unarchive:
    src: "/tmp/{{ istioctl_archive_file }}"
    dest: /tmp
  delegate_to: localhost

- name: Install istioctl binary
  copy:
    src: "/tmp/istioctl"
    dest: "{{ binary_path }}"
    mode: '0755'

- name: Get and install Lens AppImage
  get_url:
    url: "{{ k8slens_url }}"
    dest: "{{ binary_path }}"
    mode: '0755'

- name: Get and install stern binary
  get_url:
    url: "{{ stern_url }}"
    dest: "{{ binary_path }}/stern"
    mode: '0755'

- name: Get kustomize
  get_url:
    url: "{{ kustomize_url }}"
    dest: /tmp
  delegate_to: localhost

- name: Unarchive kustomize
  unarchive:
    src: "/tmp/{{ kustomize_archive_file }}"
    dest: /tmp
  delegate_to: localhost

- name: Install kustomize binary
  copy:
    src: "/tmp/kustomize"
    dest: "{{ binary_path }}"
    mode: '0755'

- name: Get kubeval
  get_url:
    url: "{{ kubeval_url }}"
    dest: /tmp
  delegate_to: localhost

- name: Unarchive kubeval
  unarchive:
    src: "/tmp/{{ kubeval_archive_file }}"
    dest: /tmp
  delegate_to: localhost

- name: Install kubeval binary
  copy:
    src: "/tmp/kubeval"
    dest: "{{ binary_path }}"
    mode: '0755'

- name: Get and install calicoctl binary
  get_url:
    url: "{{ calicoctl_url }}"
    dest: "{{ binary_path }}/calicoctl"
    mode: '0755'

- name: Get kube-linter
  get_url:
    url: "{{ kubelinter_url }}"
    dest: /tmp
  delegate_to: localhost

- name: Unarchive kube-linter
  unarchive:
    src: "/tmp/{{ kubelinter_archive_file }}"
    dest: /tmp
  delegate_to: localhost

- name: Install kube-linter binary
  copy:
    src: "/tmp/kube-linter"
    dest: "{{ binary_path }}"
    mode: '0755'

- name: Get polaris
  get_url:
    url: "{{ polaris_url }}"
    dest: /tmp
  delegate_to: localhost

- name: Unarchive polaris
  unarchive:
    src: "/tmp/{{ polaris_archive_file }}"
    dest: /tmp
  delegate_to: localhost

- name: Install polaris binary
  copy:
    src: "/tmp/polaris"
    dest: "{{ binary_path }}"
    mode: '0755'

- name: Get flux
  get_url:
    url: "{{ flux_url }}"
    dest: /tmp
  delegate_to: localhost

- name: Unarchive flux
  unarchive:
    src: "/tmp/{{ flux_archive_file }}"
    dest: /tmp
  delegate_to: localhost

- name: Install flux binary
  copy:
    src: "/tmp/flux"
    dest: "{{ binary_path }}"
    mode: '0755'
