---
# tasks file for dev_tools

- name: Include checks/asserts
  include: asserts.yml

- name: Install prerequisites
  apt:
    name: "{{ ubuntu_prereqs }}"
    state: present
    update_cache: yes

- name: Enable universe repository
  apt_repository:
    repo: "deb http://pt.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release|lower }} universe"
    state: present

- name: Install Microsoft package repository
  apt:
    deb: "{{ ms_package_repository }}"

- name: Install Ubuntu packages
  apt:
    name: "{{ ubuntu_packages }}"
    state: present
    update_cache: yes

- name: Install .NET SDK
  apt:
    name: "{{ dotnet_packages }}"
    state: present
    update_cache: yes

- name: Import Microsoft APT repository key
  apt_key:
    url: "{{ vs_code_repo_key_url }}"
    state: present

- name: Add the Microsoft APT repository
  apt_repository:
#    repo: "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/trusted.gpg.d/packages.microsoft.gpg] {{ vs_code_repo_baseurl }} stable main"
    repo: "deb [arch=amd64] {{ vs_code_repo_baseurl }} stable main"
    filename: "{{ vs_code_pkg_name }}"
    update_cache_retry_max_delay: 60
    update_cache_retries: 5
    update_cache: yes
    state: present

- name: Install vs code
  apt:
    name: "{{ vs_code_pkg_name }}"
    state: present
    update_cache: yes

#- name: Install VS Code
#  community.general.snap:
#    name: code
#    classic: yes
#
#- name: Install IntelliJ IDEA
#  community.general.snap:
#    name: intellij-idea-community
#    classic: yes
#    channel: latest/edge
#
#- name: Install Insomnia
#  community.general.snap:
#    name:
#      - insomnia
#      - insomnia-designer

- name: Get and install minikube binary
  get_url:
    url: "{{ minikube_url }}"
    dest: "{{ binary_path }}/minikube"
    mode: '0755'

- name: Install pre-commit
  pip:
    name: pre-commit

- name: Install molecule
  pip:
    name: molecule[ansible,lint,docker]

- name: Get and install Obsidian AppImage
  get_url:
    url: "{{ obsidian_url }}"
    dest: "{{ binary_path }}"
    mode: '0755'

- name: Get and install TestMace AppImage
  get_url:
    url: "{{ testmace_url }}"
    dest: "{{ binary_path }}"
    mode: '0755'

- name: Install drawio desktop
  apt:
    deb: "{{ drawio_url }}"

- name: Get GitVersion
  get_url:
    url: "{{ gitversion_url }}"
    dest: /tmp
  delegate_to: localhost

- name: Unarchive GitVersion
  unarchive:
    src: "/tmp/{{ gitversion_archive_file }}"
    dest: /tmp
  delegate_to: localhost

- name: Change GitVersion binary file permissions
  ansible.builtin.file:
    path: /tmp/gitversion
    mode: '0755'
  delegate_to: localhost

- name: Change GitVersion lib file permissions
  ansible.builtin.file:
    path: /tmp/libgit2-6777db8.so
    mode: '0755'
  delegate_to: localhost

- name: Install GitVersion binary
  copy:
    src: "/tmp/gitversion"
    dest: "{{ binary_path }}"
    mode: '0755'

- name: Install GitVersion lib
  copy:
    src: "/tmp/libgit2-6777db8.so"
    dest: "{{ binary_path }}"
    mode: '0755'
