---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  vars:
    list_of_binaries:
      - kubectl
      - kubectx
      - kubens
      - fluxctl
      - istioctl
      - helm
      - stern
  tasks:
    - name: Check binaries in path
      command:
        cmd: which {{ item }}
        creates: /tmp/empty
      with_items: "{{ list_of_binaries }}"
      register: cmd_result
      failed_when: cmd_result.rc > 0
