---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  vars:
    list_of_binaries:
      - terraform
      - terragrunt
      - tflint
      - conftest
      - terraform-docs
  tasks:
    - name: Check binaries in path
      command:
        cmd: which {{ item }}
        creates: /tmp/empty
      with_items: "{{ list_of_binaries }}"
      register: cmd_result
      failed_when: cmd_result.rc > 0
