---
# defaults file for base_utils
ubuntu_packages:
  - imagemagick
  - tree
  - curl
  - wget
  - git
  - unzip
  - apt-file
  - mc
  - exuberant-ctags
  - ack-grep
  - silversearcher-ag
  - ripgrep
  - zsh
  - zsh-syntax-highlighting
  - ttf-ancient-fonts
  - fonts-powerline
  - fonts-font-awesome
  - terminator
  - tilix
  - tmux
  - build-essential
  - libssl-dev
  - libffi-dev
  - python3-pip
  - python3-dev
  - python3-venv
  - golang
  - vim
  - neovim
