---
# tasks file for i3wm

- name: print distro info
  debug: msg="{{ ansible_os_family }} > {{ ansible_distribution }} {{ ansible_distribution_version }}"

- name: Include checks/asserts
  include: asserts.yml

- name: Install i3wm packages
  apt:
    name: "{{ i3wm_packages }}"
    state: present
    update_cache: yes
