---
# tasks file for terraform_tools

- name: Include checks/asserts
  include: asserts.yml

- name: Get terraform
  get_url:
    url: "{{ terraform_url }}"
    dest: /tmp
  delegate_to: localhost

- name: Unarchive terraform
  unarchive:
    src: "/tmp/{{ terraform_archive_file }}"
    dest: /tmp
  delegate_to: localhost

- name: Install terraform binary
  copy:
    src: "/tmp/terraform"
    dest: "{{ binary_path }}"
    mode: '0755'

- name: Get and install terragrunt binary
  get_url:
    url: "{{ terragrunt_url }}"
    dest: "{{ binary_path }}/terragrunt"
    mode: '0755'

- name: Get and install OPA binary
  get_url:
    url: "{{ opa_url }}"
    dest: "{{ binary_path }}/opa"
    mode: '0755'

- name: Install conftest
  apt:
    deb: "{{ conftest_deb_url }}"

- name: Get tflint
  get_url:
    url: "{{ tflint_url }}"
    dest: /tmp
  delegate_to: localhost

- name: Unarchive tflint
  unarchive:
    src: "/tmp/{{ tflint_archive_file }}"
    dest: /tmp
  delegate_to: localhost

- name: Install tflint binary
  copy:
    src: "/tmp/tflint"
    dest: "{{ binary_path }}"
    mode: '0755'

- name: Get tflint azurerm ruleset
  get_url:
    url: "{{ tflint_azurerm_ruleset_url }}"
    dest: /tmp
  delegate_to: localhost

- name: Unarchive tflint azurerm ruleset
  unarchive:
    src: "/tmp/{{ tflint_azurerm_ruleset_archive_file }}"
    dest: /tmp
  delegate_to: localhost

- name: Install tflint azurerm ruleset binary
  become: false
  copy:
    src: "/tmp/tflint-ruleset-azurerm"
    dest: $HOME/.tflint.d/plugins/
    mode: '0755'

- name: tflint plugins configuration
  become: false
  template:
    src: tflint.hcl.j2
    dest: $HOME/.tflint.hcl
    mode: u=rw,g=r,o=r

- name: Get and install terraform-docs binary
  get_url:
    url: "{{ terraform_docs_url }}"
    dest: "{{ binary_path }}/terraform-docs"
    mode: '0755'

- name: Get and install tfsec binary
  get_url:
    url: "{{ tfsec_url }}"
    dest: "{{ binary_path }}/tfsec"
    mode: '0755'

- name: Get and install tfsec-checkgen binary
  get_url:
    url: "{{ tfsec_checkgen_url }}"
    dest: "{{ binary_path }}/tfsec-checkgen"
    mode: '0755'

- name: Get and install sops binary
  get_url:
    url: "{{ sops_url }}"
    dest: "{{ binary_path }}/sops"
    mode: '0755'
