---
# tasks file for base_utils

- name: print distro info
  debug: msg="{{ ansible_os_family }} > {{ ansible_distribution }} {{ ansible_distribution_version }}"

- name: Include checks/asserts
  include: asserts.yml

- name: Install Ubuntu packages
  apt:
    name: "{{ ubuntu_packages }}"
    state: present
    update_cache: yes
