---
# tasks file for base_utils

- name: Include checks/asserts
  include: asserts.yml

- name: Install Ubuntu packages
  apt:
    name: "{{ ubuntu_packages }}"
    state: present
    update_cache: yes

- name: Install pip packages
  pip:
    name: "{{ pip_packages }}"
