---
# tasks file for cloud_tools

- name: Include checks/asserts
  include: asserts.yml

- name: Install dependencies
  apt:
    name: "{{ dependencies_pkg }}"
    state: present
    update_cache: yes

- name: Install aws-cli
  apt:
    name: "{{ aws_cli_pkg_name }}"
    state: present
    update_cache: yes

- name: Import Microsoft APT repository key
  apt_key:
    url: "{{ ms_azure_cli_repo_key_url }}"
    state: present

- name: Add the Microsoft APT repository
  apt_repository:
    repo: "deb [arch=amd64] {{ ms_azure_cli_repo_baseurl }} {{ ansible_distribution_release }} main"
    filename: "{{ azure_cli_pkg_name }}"
    update_cache_retry_max_delay: 60
    update_cache_retries: 5
    update_cache: yes
    state: present

- name: Install azure-cli
  apt:
    name: "{{ azure_cli_pkg_name }}"
    state: present
    update_cache: yes
