---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: true
  vars:
    list_of_packages:
      - "'awscli' in ansible_facts.packages"
      - "'azure-cli' in ansible_facts.packages"
  tasks:
    - name: Gather the package manager facts
      package_facts:
        manager: auto
    - name: Assert that following packages are installed
      assert:
        that: "{{ list_of_packages }}"
